name: deploy-to-224
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: Prod
    env:
      SSH_KEY: /home/actions-runner/.ssh/id_rsa
    steps:
      - uses: actions/checkout@v4

      - name: Add target to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 "${{ vars.TARGET_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync code -> target
        run: |
          rsync -az --delete \
            --exclude ".git/" --exclude ".github/" \
            -e "ssh -i $SSH_KEY -o StrictHostKeyChecking=no" \
            ./ "${{ vars.TARGET_USER }}@${{ vars.TARGET_HOST }}:${{ vars.TARGET_PATH }}/"

      - name: Remote post-deploy: build & up
        run: |
          ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no \
            "${{ vars.TARGET_USER }}@${{ vars.TARGET_HOST }}" 'bash -s' <<'REMOTE'
          set -e
          cd "${{ vars.TARGET_PATH }}"
          # (если нужно) зависимости приложений здесь: composer/npm и т.п.

          # docker compose (код уже в /var/www/deploy)
          docker compose pull || true
          docker compose build
          docker compose up -d
          docker image prune -af || true
          REMOTE
